# Pipeline name
name: 'Deploying to Heroku'

# Execute on push master
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "next-app-frontend" #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}